sudo: required

language: android
jdk: oraclejdk8

env:
 global:
    - ANDROID_TARGET_21=android-21
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.2
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET_21}

before_install:
 - chmod +x gradlew
 - pip install --user codecov

script:
    # Create an emulator.
  - echo no | android create avd --force -n test2 -t ${ANDROID_TARGET_21} --abi ${ANDROID_ABI}

    # Start the first emulator.
  - emulator -avd test2 -no-skin -no-audio -no-window &
  - sh scripts/wait-for-emulator.sh

    # Just to check whether the device is seen by ADB.
  - "adb devices"

    # Unlock the device.
  - adb -s emulator-5554 shell input keyevent 82 &

    # Run the script.
  - sh scripts/script.sh

notifications:
  email: true

after_failure:
  - "cat /home/travis/build/zsavely/ClipdAndroid/clipdapp/build/outputs/lint-results-debug.xml"
  - "cat /home/travis/build/zsavely/ClipdAndroid/clipdapp/build/outputs/lint-results-release.xml"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - sh set_tags.sh
  - codecov

deploy:
  provider: releases
  api_key:
    secure: R3U1icl6nCRVN/6GwfQ4hW14HqhYGSF37mDCAqhvJo3OCNdrQhrUVOOB918qP8ljOoZAymjKphNHgtkUEgD4ZzktGOQv9rznZzKfy0SjFGB+jTu4PNk7BIg6qBfY78bYNEROEAG+68hmfZy/MasY/9um7IZ+VNnTEITee94tzOJ6ZZp24pf9hX3J7tiW1qzf7DCBQLdrwI2qHlHU+NHXSVdliydzLBELVU4yLOzrEDys9mK/v7MlariEFFv71sD+P6U6nzEOckyg2v50dEgtefhk+2SICJJxv9nPucb0WcBJur/RkA4p92W/r7GylqzueXctUTQSGDd8hByz7lIaP2MffWfeBy+rojWF9IGrjSr/guPUp8ITdfKWcC0Ykf+dkEkEju02Jy4WmBaoVIqwH1Gx5TpHnjvvDO477veGCIrL8gXa/U4XUvWfco6+f/BIqkI3FlOl2TQ1qToRgDg6a37eobKgZuCdOB59UIqkUy3aTLJ5vHwK75VRYguBUTiN5eAehYmol3OV7KGyWyiBw9glx4X2uuTpmusY/CTK1rAGXqaTJ9n2VRV5vBbCh28P2M8cISttsnDhDx5VG0r3z5sA/0jGGQNfl475WEKz0LKXIX8g5gL7RUlUfRh1mRmcdPWxyuGSiIPzHtRTmTJt+iiW8iZZMj17oIdaI5A4WdY=
  file: "github-client/build/outputs/apk/github-client*release*.apk"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    repo: zsavely/GitHubClient
